[package]
name = "noirc_evaluator"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noirc_frontend = { path = "../noirc_frontend" }
noirc_errors = { path = "../noirc_errors" }
noirc_abi = { path = "../noirc_abi" }
acvm = { git = "https://github.com/noir-lang/noir" }
arena = { path = "../arena" }
fm = { path = "../fm" }
lazy_static = "1.4.0"
thiserror = "1.0.21"
num-bigint = "0.4"
num-traits = "0.2.8"

[features]
std = ["fm/std"]
wasm = ["fm/wasm"]
bn254_std = ["acvm/bn254", "noirc_frontend/bn254", "noirc_abi/bn254", "std"]
bn254_wasm = ["acvm/bn254", "noirc_frontend/bn254", "noirc_abi/bn254", "wasm"]
bls12_381_std = ["acvm/bls12_381", "noirc_frontend/bls12_381", "noirc_abi/bls12_381", "std"]
bls12_381_wasm = ["acvm/bls12_381", "noirc_frontend/bls12_381", "noirc_abi/bls12_381", "wasm"]
